### ISSUE TITLE
Entities (Pacman)

### ISSUE THREAD

**Issue by jackson-dahl42** [UserC2/ICS4U-Pac-Man#8]
**Requirement Description**
The entities include Pacman and the ghosts.
An entity has a coordinate on the grid or the tile it is occupying.
An entity has a direction it is moving in (its next tile).
An entity has collisions.

Pacman:
Pacman takes player inputs.
Pacman can interact with items and entities.

Ghosts
Ghosts have 4 modes and ai to be worked on later.

**Potential Implementation**
Work on Pacman first: 
Pacman is the same size as a tile on a grid.
Pacman moves from one tile to the next.
An animation happens as he crosses tiles to make it look smooth.
His speed can be controlled by the time it takes to move to the next tile.
(This is the movement in the original game)
Add conditions on when Pacman can turn or move ex.(turning buffer, can't turn into walls, stops when wall in next tile)

**Comment by l2lam** [comment]
Entity is a very generic term... what would you call the Cherry, pellets, power pellets?   They also share things in common with pacman and ghosts.

"Having collisions" sounds weird. Your entity can collide with other things, it is an action that changes its properties.
