### ISSUE TITLE
Program pacman movement

### ISSUE THREAD

**Issue by UserC2** [UserC2/ICS4U-Pac-Man#9]
**Requirement Description**
* Determine how Pac Man should move (comment ideas here)
* Implement this movement type.

**Comment by jackson-dahl42** [comment]
1st way: Pacman has a x and y and a velocity and he is bound by the walls if Pacman is inside a wall it pushes him out. The walls or maze constrain his movement.
2nd way: Pacman's movement is constrained to nodes so he moves from one node to the next.
3rd way: Pacman moves one grid space at a time based on his direction and the sprite is just an animation/interpolation of where he is.

**Comment by UserC2** [comment]
Closed by #22
